import type {
  HobbyPreset,
  HobbyPresetMetricTemplate,
  HobbyPresetPipelineStep,
  HobbyPresetRecipeField,
} from "@lifekeeper/types";

const hobbyPreset = (input: HobbyPreset): HobbyPreset => ({ ...input });

const hobbyMetric = (
  input: Omit<HobbyPresetMetricTemplate, "metricType"> & Partial<Pick<HobbyPresetMetricTemplate, "metricType">>
): HobbyPresetMetricTemplate => ({ metricType: "numeric", ...input });

const pipelineStep = (
  label: string,
  sortOrder: number,
  options?: { color?: string; isFinal?: boolean }
): HobbyPresetPipelineStep => ({
  label,
  sortOrder,
  ...(options?.color ? { color: options.color } : {}),
  isFinal: options?.isFinal ?? false,
});

const recipeField = (
  input: Omit<HobbyPresetRecipeField, "options"> & Partial<Pick<HobbyPresetRecipeField, "options">>
): HobbyPresetRecipeField => ({ options: [], ...input });

export const hobbyPresetLibrary: HobbyPreset[] = [
  hobbyPreset({
    key: "beer-brewing",
    label: "Beer Brewing",
    description: "Homebrewing beer — all-grain, extract, or BIAB. Full pipeline from brew day through conditioning.",
    lifecycleMode: "pipeline",
    tags: ["brewing", "beer", "fermentation", "homebrewing"],

    suggestedCustomFields: [
      {
        key: "brewingMethod",
        label: "Brewing Method",
        type: "select",
        required: false,
        options: ["All-Grain", "Extract", "BIAB (Brew in a Bag)", "Partial Mash"],
        wide: false,
        order: 0,
      },
      {
        key: "defaultBatchSize",
        label: "Default Batch Size (gallons)",
        type: "number",
        required: false,
        options: [],
        wide: false,
        order: 1,
      },
      {
        key: "fermentationVesselType",
        label: "Fermentation Vessel Type",
        type: "select",
        required: false,
        options: ["Bucket", "Carboy", "Conical", "Unitank"],
        wide: false,
        order: 2,
      },
      {
        key: "carbonationMethod",
        label: "Carbonation Method",
        type: "select",
        required: false,
        options: ["Bottle Conditioning", "Forced (Keg)", "Natural"],
        wide: false,
        order: 3,
      },
      {
        key: "waterSource",
        label: "Water Source",
        type: "select",
        required: false,
        options: ["Municipal", "Well", "Spring", "RO/Distilled"],
        wide: false,
        order: 4,
      },
      {
        key: "brewhouse",
        label: "Brewhouse",
        type: "string",
        required: false,
        options: [],
        wide: false,
        order: 5,
      },
    ],

    pipelineSteps: [
      pipelineStep("Planned", 0, { color: "gray" }),
      pipelineStep("Brew Day", 1, { color: "blue" }),
      pipelineStep("Primary Fermentation", 2, { color: "amber" }),
      pipelineStep("Secondary / Dry Hop", 3, { color: "amber" }),
      pipelineStep("Cold Crash / Clarification", 4, { color: "cyan" }),
      pipelineStep("Packaging", 5, { color: "green" }),
      pipelineStep("Conditioning / Carbonating", 6, { color: "green" }),
      pipelineStep("Ready / Aging", 7, { color: "teal" }),
      pipelineStep("Completed", 8, { color: "green", isFinal: true }),
    ],

    metricTemplates: [
      hobbyMetric({ key: "og", name: "Original Gravity (OG)", unit: "SG", metricType: "gravity" }),
      hobbyMetric({ key: "fg", name: "Final Gravity (FG)", unit: "SG", metricType: "gravity" }),
      hobbyMetric({ key: "ph", name: "pH", unit: "pH", metricType: "ph" }),
      hobbyMetric({ key: "fermentation-temp", name: "Fermentation Temperature", unit: "°F", metricType: "temperature" }),
      hobbyMetric({ key: "batch-volume", name: "Batch Volume", unit: "gal" }),
      hobbyMetric({ key: "pre-boil-gravity", name: "Pre-Boil Gravity", unit: "SG", metricType: "gravity" }),
      hobbyMetric({ key: "mash-temp", name: "Mash Temperature", unit: "°F", metricType: "temperature" }),
    ],

    inventoryCategories: [
      "Base Malts",
      "Specialty Malts",
      "Hops",
      "Yeast",
      "Adjuncts & Sugars",
      "Water Chemistry",
      "Fining Agents",
      "Priming Sugar",
      "Sanitizer & Cleaning",
      "Bottling / Kegging Supplies",
    ],

    recipeFields: [
      recipeField({ key: "bjcpStyle", label: "BJCP Style", type: "string", helpText: "e.g. 10A - American Pale Ale", group: "Style" }),
      recipeField({ key: "targetOG", label: "Target OG", type: "number", unit: "SG", group: "Targets" }),
      recipeField({ key: "targetFG", label: "Target FG", type: "number", unit: "SG", group: "Targets" }),
      recipeField({ key: "targetABV", label: "Target ABV", type: "number", unit: "%", group: "Targets" }),
      recipeField({ key: "targetIBU", label: "Target IBU", type: "number", unit: "IBU", group: "Targets" }),
      recipeField({ key: "targetSRM", label: "Target SRM", type: "number", unit: "SRM", group: "Targets" }),
      recipeField({ key: "mashTemp", label: "Mash Temperature", type: "number", unit: "°F", group: "Process" }),
      recipeField({ key: "mashDuration", label: "Mash Duration", type: "number", unit: "min", group: "Process" }),
      recipeField({ key: "boilDuration", label: "Boil Duration", type: "number", unit: "min", group: "Process" }),
      recipeField({ key: "fermTempLow", label: "Ferm Temp Low", type: "number", unit: "°F", group: "Process" }),
      recipeField({ key: "fermTempHigh", label: "Ferm Temp High", type: "number", unit: "°F", group: "Process" }),
      recipeField({ key: "carbonationLevel", label: "Carbonation Level", type: "number", unit: "volumes CO2", group: "Packaging" }),
      recipeField({ key: "waterProfile", label: "Water Profile", type: "string", helpText: "Target water chemistry or style (e.g., Burton, Pilsen)", group: "Water" }),
    ],

    suggestedEquipment: [
      "Brew Kettle",
      "Mash Tun",
      "Hot Liquor Tank",
      "Fermenter (Primary)",
      "Fermenter (Secondary)",
      "Keg System",
      "Bottle Filler / Capper",
      "Wort Chiller",
      "Temperature Controller",
      "Hydrometer / Refractometer",
      "pH Meter",
      "Grain Mill",
      "Auto-Siphon / Transfer Pump",
      "CO2 Tank & Regulator",
      "Cleaning Bucket / Spray",
    ],

    sessionStepTypes: [
      "mash",
      "boil",
      "chill",
      "pitch",
      "ferment",
      "dry-hop",
      "cold-crash",
      "package",
      "condition",
    ],

    starterRecipes: [
      {
        name: "Simple American Pale Ale",
        description: "A straightforward APA — clean malt backbone, citrusy American hops, and a crisp finish.",
        styleCategory: "10A - American Pale Ale",
        ingredients: [
          { name: "Pale Malt (2-Row)", quantity: 9, unit: "lb", category: "Base Malts" },
          { name: "Crystal 40L", quantity: 1, unit: "lb", category: "Specialty Malts" },
          { name: "Munich Malt", quantity: 0.5, unit: "lb", category: "Specialty Malts" },
          { name: "Cascade (60 min)", quantity: 1, unit: "oz", category: "Hops" },
          { name: "Cascade (15 min)", quantity: 1, unit: "oz", category: "Hops" },
          { name: "Cascade (0 min / flameout)", quantity: 1, unit: "oz", category: "Hops" },
          { name: "US-05 / Safale American Ale Yeast", quantity: 1, unit: "packet", category: "Yeast" },
          { name: "Irish Moss (15 min)", quantity: 1, unit: "tsp", category: "Fining Agents" },
          { name: "Priming Sugar (if bottling)", quantity: 5, unit: "oz", category: "Priming Sugar" },
        ],
        steps: [
          { title: "Heat Strike Water", description: "Heat 4 gallons to 164°F for a target mash temp of 152°F.", stepType: "mash", durationMinutes: 15 },
          { title: "Mash In", description: "Add grain to strike water, stir to eliminate dough balls. Hold at 152°F.", stepType: "mash", durationMinutes: 60 },
          { title: "Mash Out", description: "Raise to 168°F and hold for 10 minutes to halt enzymatic activity.", stepType: "mash", durationMinutes: 10 },
          { title: "Sparge", description: "Batch sparge or fly sparge with 170°F water to collect ~6.5 gallons.", stepType: "mash", durationMinutes: 20 },
          { title: "Bring to Boil", description: "Bring wort to a rolling boil. Watch for hot break.", stepType: "boil", durationMinutes: 10 },
          { title: "60-Minute Hop Addition", description: "Add 1 oz Cascade. Start 60-minute boil timer.", stepType: "boil", durationMinutes: 45 },
          { title: "15-Minute Additions", description: "Add 1 oz Cascade and 1 tsp Irish Moss with 15 minutes remaining.", stepType: "boil", durationMinutes: 15 },
          { title: "Flameout Hops", description: "Kill heat. Add 1 oz Cascade at flameout. Steep 10 minutes.", stepType: "boil", durationMinutes: 10 },
          { title: "Chill Wort", description: "Chill to 66°F as quickly as possible using wort chiller.", stepType: "chill", durationMinutes: 20 },
          { title: "Transfer & Pitch Yeast", description: "Transfer to fermenter, leaving trub behind. Aerate well. Pitch yeast.", stepType: "pitch", durationMinutes: 15 },
          { title: "Primary Fermentation", description: "Ferment at 64–68°F for 10–14 days until activity slows and gravity is stable.", stepType: "ferment" },
          { title: "Package", description: "Bottle with priming sugar or keg and force carbonate to 2.4 volumes CO2.", stepType: "package", durationMinutes: 30 },
          { title: "Condition", description: "Bottle condition 2 weeks at room temp, or keg condition 3–5 days cold.", stepType: "condition" },
        ],
        customFields: {
          bjcpStyle: "10A - American Pale Ale",
          targetOG: 1.052,
          targetFG: 1.012,
          targetABV: 5.2,
          targetIBU: 40,
          targetSRM: 7,
          mashTemp: 152,
          mashDuration: 60,
          boilDuration: 60,
          fermTempLow: 64,
          fermTempHigh: 68,
          carbonationLevel: 2.4,
          waterProfile: "Balanced",
        },
      },
    ],
  }),
  hobbyPreset({
    key: "3d-printing",
    label: "3D Printing (FDM/Resin)",
    description: "FDM and resin 3D printing — print profiles, spool tracking, printer maintenance, and quality logging.",
    lifecycleMode: "pipeline",
    tags: ["3d-printing", "fdm", "resin", "additive-manufacturing", "maker"],

    suggestedCustomFields: [
      {
        key: "primaryPrinterModel",
        label: "Primary Printer Model",
        type: "string",
        required: false,
        options: [],
        wide: false,
        order: 0,
      },
      {
        key: "printerType",
        label: "Printer Type",
        type: "select",
        required: false,
        options: ["FDM", "Resin (SLA/MSLA/DLP)", "Both"],
        wide: false,
        order: 1,
      },
      {
        key: "buildVolumeX",
        label: "Build Volume X (mm)",
        type: "number",
        required: false,
        options: [],
        wide: false,
        order: 2,
      },
      {
        key: "buildVolumeY",
        label: "Build Volume Y (mm)",
        type: "number",
        required: false,
        options: [],
        wide: false,
        order: 3,
      },
      {
        key: "buildVolumeZ",
        label: "Build Volume Z (mm)",
        type: "number",
        required: false,
        options: [],
        wide: false,
        order: 4,
      },
      {
        key: "primarySlicer",
        label: "Primary Slicer",
        type: "select",
        required: false,
        options: ["Cura", "PrusaSlicer", "OrcaSlicer", "BambuStudio", "Simplify3D", "ChiTuBox", "Lychee Slicer", "Other"],
        wide: false,
        order: 5,
      },
      {
        key: "enclosureType",
        label: "Enclosure Type",
        type: "select",
        required: false,
        options: ["None", "Stock Enclosure", "DIY Enclosure", "Heated Chamber"],
        wide: false,
        order: 6,
      },
      {
        key: "filamentDryerAvailable",
        label: "Filament Dryer Available",
        type: "select",
        required: false,
        options: ["Yes", "No"],
        wide: false,
        order: 7,
      },
    ],

    pipelineSteps: [
      pipelineStep("Slicing", 0, { color: "gray" }),
      pipelineStep("Printer Prep", 1, { color: "blue" }),
      pipelineStep("Printing", 2, { color: "amber" }),
      pipelineStep("Cooling", 3, { color: "cyan" }),
      pipelineStep("Post-Processing", 4, { color: "teal" }),
      pipelineStep("Quality Check", 5, { color: "green" }),
      pipelineStep("Completed", 6, { color: "green", isFinal: true }),
    ],

    metricTemplates: [
      hobbyMetric({
        key: "print-time",
        name: "Print Time",
        unit: "min",
        description: "Actual print duration in minutes",
      }),
      hobbyMetric({
        key: "filament-used",
        name: "Filament Used",
        unit: "g",
        description: "Weight of filament consumed",
      }),
      hobbyMetric({
        key: "first-layer-adhesion",
        name: "First Layer Adhesion",
        unit: "score",
        description: "1-5 rating of first layer quality",
      }),
      hobbyMetric({
        key: "surface-quality",
        name: "Surface Quality",
        unit: "score",
        description: "1-5 rating of overall surface finish",
      }),
      hobbyMetric({
        key: "dimensional-accuracy",
        name: "Dimensional Accuracy",
        unit: "mm",
        description: "Deviation from designed dimensions",
      }),
      hobbyMetric({
        key: "nozzle-temp-actual",
        name: "Nozzle Temp (Actual)",
        unit: "°C",
        metricType: "temperature",
        description: "Actual hotend temperature during print",
      }),
      hobbyMetric({
        key: "bed-temp-actual",
        name: "Bed Temp (Actual)",
        unit: "°C",
        metricType: "temperature",
        description: "Actual bed temperature during print",
      }),
      hobbyMetric({
        key: "ambient-temp",
        name: "Ambient Temperature",
        unit: "°C",
        metricType: "temperature",
        description: "Room or enclosure temperature",
      }),
      hobbyMetric({
        key: "material-cost",
        name: "Material Cost",
        unit: "$",
        description: "Cost of filament/resin consumed",
      }),
      hobbyMetric({
        key: "print-success",
        name: "Print Success",
        unit: "pass/fail",
        description: "1 for success, 0 for failure — used for success rate tracking",
      }),
    ],

    inventoryCategories: [
      "PLA Filament",
      "PETG Filament",
      "ABS / ASA Filament",
      "TPU Filament",
      "Specialty Filament",
      "Resin — Standard",
      "Resin — Engineering",
      "Nozzles",
      "Build Plates & Surfaces",
      "Adhesives & Release Agents",
      "Post-Processing Supplies",
      "Printer Parts & Maintenance",
    ],

    recipeFields: [
      recipeField({
        key: "material",
        label: "Material",
        type: "select",
        options: [
          "PLA",
          "PLA+",
          "PETG",
          "ABS",
          "ASA",
          "TPU",
          "Nylon",
          "PC",
          "PVA",
          "CF-PLA",
          "CF-PETG",
          "Standard Resin",
          "ABS-Like Resin",
          "Water Washable Resin",
          "Tough Resin",
          "Flexible Resin",
        ],
        group: "Material",
      }),
      recipeField({
        key: "materialBrand",
        label: "Material Brand",
        type: "string",
        helpText: "e.g., Hatchbox, eSun, Prusament, Elegoo",
        group: "Material",
      }),
      recipeField({ key: "materialColor", label: "Material Color", type: "string", group: "Material" }),
      recipeField({
        key: "nozzleSize",
        label: "Nozzle Size",
        type: "number",
        unit: "mm",
        helpText: "e.g., 0.4, 0.6, 0.8",
        group: "Print Settings",
      }),
      recipeField({
        key: "layerHeight",
        label: "Layer Height",
        type: "number",
        unit: "mm",
        helpText: "e.g., 0.2 for standard, 0.12 for fine",
        group: "Print Settings",
      }),
      recipeField({ key: "nozzleTemp", label: "Nozzle Temperature", type: "number", unit: "°C", group: "Temperatures" }),
      recipeField({ key: "bedTemp", label: "Bed Temperature", type: "number", unit: "°C", group: "Temperatures" }),
      recipeField({ key: "printSpeed", label: "Print Speed", type: "number", unit: "mm/s", group: "Print Settings" }),
      recipeField({ key: "infillPercent", label: "Infill Percentage", type: "number", unit: "%", group: "Print Settings" }),
      recipeField({
        key: "infillPattern",
        label: "Infill Pattern",
        type: "select",
        options: ["Grid", "Gyroid", "Cubic", "Lines", "Triangles", "Honeycomb", "Lightning", "Adaptive Cubic"],
        group: "Print Settings",
      }),
      recipeField({
        key: "wallCount",
        label: "Wall Count",
        type: "number",
        helpText: "Number of perimeter walls",
        group: "Print Settings",
      }),
      recipeField({ key: "topBottomLayers", label: "Top/Bottom Layers", type: "number", group: "Print Settings" }),
      recipeField({
        key: "supportType",
        label: "Support Type",
        type: "select",
        options: ["None", "Normal", "Tree", "Organic", "Paint-On"],
        group: "Supports & Adhesion",
      }),
      recipeField({
        key: "adhesionType",
        label: "Bed Adhesion Type",
        type: "select",
        options: ["None", "Skirt", "Brim", "Raft"],
        group: "Supports & Adhesion",
      }),
      recipeField({ key: "retractDistance", label: "Retraction Distance", type: "number", unit: "mm", group: "Retraction" }),
      recipeField({ key: "retractSpeed", label: "Retraction Speed", type: "number", unit: "mm/s", group: "Retraction" }),
      recipeField({
        key: "coolingFanSpeed",
        label: "Cooling Fan Speed",
        type: "number",
        unit: "%",
        helpText: "0-100",
        group: "Cooling",
      }),
      recipeField({
        key: "estimatedPrintTime",
        label: "Estimated Print Time (slicer)",
        type: "string",
        helpText: "From slicer estimate, e.g., 4h 32m",
        group: "Estimates",
      }),
      recipeField({
        key: "estimatedFilamentWeight",
        label: "Estimated Filament (slicer)",
        type: "number",
        unit: "g",
        group: "Estimates",
      }),
      recipeField({
        key: "modelSource",
        label: "Model Source",
        type: "select",
        options: ["Original Design", "Thingiverse", "Printables", "Thangs", "MyMiniFactory", "Cults3D", "Other"],
        group: "Source",
      }),
      recipeField({
        key: "modelUrl",
        label: "Model URL",
        type: "string",
        helpText: "Link to the original model file or download page",
        group: "Source",
      }),
    ],

    suggestedEquipment: [
      "3D Printer (FDM)",
      "3D Printer (Resin)",
      "Filament Dryer",
      "Wash & Cure Station",
      "Digital Calipers",
      "Deburring / Flush Cutters",
      "Scraper / Spatula Set",
      "Heat Gun",
      "Needle Files",
      "Sandpaper Set (various grits)",
      "IPA for Resin Cleaning",
      "Build Plate (spare)",
      "Nozzle Cleaning Needles",
      "PTFE Tube / Bowden Fittings",
      "Enclosure / Tent",
      "Webcam / Print Monitor",
    ],

    sessionStepTypes: [
      "slice",
      "prep",
      "print",
      "cool",
      "remove",
      "clean",
      "cure",
      "sand",
      "prime",
      "paint",
      "assemble",
      "inspect",
      "test-fit",
    ],

    starterRecipes: [
      {
        name: "PLA Standard Profile — 0.2mm",
        description: "Reliable general-purpose PLA profile. 0.2mm layer height, moderate speed, good for most prints.",
        styleCategory: "PLA — Standard",
        ingredients: [
          {
            name: "PLA Filament",
            quantity: 50,
            unit: "g",
            category: "PLA Filament",
            notes: "Estimated for a medium print — adjust per slicer estimate",
          },
        ],
        steps: [
          {
            title: "Load Model in Slicer",
            description: "Import STL/3MF into your slicer. Orient the model for best print quality — minimize overhangs and support contact with visible surfaces.",
            stepType: "slice",
            durationMinutes: 10,
          },
          {
            title: "Configure Print Settings",
            description: "Apply this profile's settings: 0.2mm layer height, 210°C nozzle, 60°C bed, 50mm/s print speed, 20% gyroid infill, 4 walls, 5 top/bottom layers. Adjust supports and adhesion based on the model geometry.",
            stepType: "slice",
            durationMinutes: 10,
          },
          {
            title: "Slice and Export",
            description: "Slice the model. Review layer preview for issues — check first layer, overhangs, support placement, and estimated print time. Export gcode to SD card or send to printer.",
            stepType: "slice",
            durationMinutes: 5,
          },
          {
            title: "Prep Printer",
            description: "Clean build plate with IPA. Verify bed is leveled (run ABL if equipped). Load filament and confirm extrusion. Pre-heat to target temps.",
            stepType: "prep",
            durationMinutes: 10,
          },
          {
            title: "Start Print — Monitor First Layer",
            description: "Start the print. Watch the entire first layer. Check for consistent squish, good adhesion, and no gaps or over-extrusion. Abort and re-level if the first layer is poor.",
            stepType: "print",
            durationMinutes: 15,
          },
          {
            title: "Print in Progress",
            description: "Monitor periodically. Check for layer shifts, stringing, spaghetti failures, or detachment from bed. Most failures happen in the first 30 minutes.",
            stepType: "print",
            durationMinutes: undefined,
          },
          {
            title: "Cooling",
            description: "Allow the print and bed to cool to room temperature before removal. PLA pops off most build surfaces cleanly when fully cooled.",
            stepType: "cool",
            durationMinutes: 20,
          },
          {
            title: "Remove Print",
            description: "Remove the print from the build plate. Use a scraper if needed but be careful not to gouge the plate or the print.",
            stepType: "remove",
            durationMinutes: 5,
          },
          {
            title: "Remove Supports",
            description: "Carefully remove support material. Use flush cutters for the bulk, then needle files or a deburring tool for contact points. Skip this step if no supports were used.",
            stepType: "clean",
            durationMinutes: 15,
          },
          {
            title: "Inspect & Measure",
            description: "Visual inspection for defects — layer lines, stringing, blobs, warping, elephant's foot. Measure critical dimensions with calipers if this is a functional part.",
            stepType: "inspect",
            durationMinutes: 10,
          },
        ],
        customFields: {
          material: "PLA",
          nozzleSize: 0.4,
          layerHeight: 0.2,
          nozzleTemp: 210,
          bedTemp: 60,
          printSpeed: 50,
          infillPercent: 20,
          infillPattern: "Gyroid",
          wallCount: 4,
          topBottomLayers: 5,
          supportType: "None",
          adhesionType: "Skirt",
          retractDistance: 0.8,
          retractSpeed: 45,
          coolingFanSpeed: 100,
          modelSource: "Original Design",
        },
      },
      {
        name: "PETG Functional Parts — 0.2mm",
        description: "PETG profile tuned for functional parts that need heat resistance and durability. Slightly slower speeds, reduced cooling.",
        styleCategory: "PETG — Functional",
        ingredients: [
          {
            name: "PETG Filament",
            quantity: 75,
            unit: "g",
            category: "PETG Filament",
            notes: "Estimated for a medium-large functional part",
          },
        ],
        steps: [
          {
            title: "Load Model in Slicer",
            description: "Import the model. Orient for strength — layer lines should run perpendicular to expected stress direction on functional parts.",
            stepType: "slice",
            durationMinutes: 10,
          },
          {
            title: "Configure PETG Settings",
            description: "Apply PETG settings: 0.2mm layer height, 235°C nozzle, 80°C bed, 40mm/s print speed, 40% grid infill (stronger for functional loads), 4 walls, 6 top/bottom layers. Use brim for bed adhesion — PETG warps more than PLA.",
            stepType: "slice",
            durationMinutes: 10,
          },
          {
            title: "Slice and Export",
            description: "Slice and review. Pay extra attention to bridging and overhang sections — PETG sags more than PLA on long unsupported spans. Add supports if needed.",
            stepType: "slice",
            durationMinutes: 5,
          },
          {
            title: "Prep Printer for PETG",
            description: "Clean plate thoroughly with IPA. PETG bonds aggressively to bare PEI/glass — apply a thin layer of glue stick or use a textured PEI sheet to prevent permanent bonding. Load PETG, purge until color is clean.",
            stepType: "prep",
            durationMinutes: 15,
          },
          {
            title: "Start Print — First Layer Check",
            description: "Start print. PETG first layer should be slightly less squished than PLA — if it is too close the nozzle will dig and leave marks. Watch for good adhesion without gouging.",
            stepType: "print",
            durationMinutes: 15,
          },
          {
            title: "Print in Progress",
            description: "PETG strings more than PLA — some stringing is normal and can be cleaned in post-processing. Watch for layer adhesion issues if the enclosure is cold.",
            stepType: "print",
            durationMinutes: undefined,
          },
          {
            title: "Cooling",
            description: "Let the bed cool to at least 40°C. PETG often releases cleanly from textured PEI at around 35–40°C. Do not force it off a hot plate.",
            stepType: "cool",
            durationMinutes: 30,
          },
          {
            title: "Remove & Clean",
            description: "Remove print. Clean stringing with a heat gun on low setting (briefly wave over the print) or carefully trim with flush cutters.",
            stepType: "clean",
            durationMinutes: 15,
          },
          {
            title: "Functional Test",
            description: "For functional parts: test fit, load test, heat exposure test, or assembly check as appropriate. Document any dimensional issues for profile tuning.",
            stepType: "inspect",
            durationMinutes: 15,
          },
        ],
        customFields: {
          material: "PETG",
          nozzleSize: 0.4,
          layerHeight: 0.2,
          nozzleTemp: 235,
          bedTemp: 80,
          printSpeed: 40,
          infillPercent: 40,
          infillPattern: "Grid",
          wallCount: 4,
          topBottomLayers: 6,
          supportType: "None",
          adhesionType: "Brim",
          retractDistance: 1.0,
          retractSpeed: 40,
          coolingFanSpeed: 50,
          modelSource: "Original Design",
        },
      },
    ],
  }),
  hobbyPreset({
    key: "reloading",
    label: "Reloading (Ammunition)",
    description: "Handloading rifle, pistol, and shotshell ammunition — load development, component tracking, and ballistic data logging.",
    lifecycleMode: "pipeline",
    tags: ["reloading", "ammunition", "handloading", "shooting", "ballistics", "precision"],

    suggestedCustomFields: [
      {
        key: "pressType",
        label: "Press Type",
        type: "select",
        required: false,
        options: ["Single Stage", "Turret", "Progressive", "Hand Press"],
        wide: false,
        order: 0,
      },
      {
        key: "pressModel",
        label: "Press Model",
        type: "string",
        required: false,
        options: [],
        wide: false,
        order: 1,
      },
      {
        key: "primaryCartridge",
        label: "Primary Cartridge",
        type: "string",
        required: false,
        options: [],
        wide: false,
        order: 2,
        helpText: "e.g., 6.5 Creedmoor, .308 Win, 9mm Luger",
      },
      {
        key: "scaleType",
        label: "Scale Type",
        type: "select",
        required: false,
        options: ["Beam Balance", "Digital", "Trickler/Thrower Combo", "Auto-Dispenser"],
        wide: false,
        order: 3,
      },
      {
        key: "scaleModel",
        label: "Scale Model",
        type: "string",
        required: false,
        options: [],
        wide: false,
        order: 4,
      },
      {
        key: "chronographModel",
        label: "Chronograph Model",
        type: "string",
        required: false,
        options: [],
        wide: false,
        order: 5,
        helpText: "e.g., LabRadar, MagnetoSpeed, Caldwell",
      },
      {
        key: "trimMethod",
        label: "Case Trim Method",
        type: "select",
        required: false,
        options: ["Manual Trimmer", "Power Trimmer", "Trim Die", "None — Pistol Only"],
        wide: false,
        order: 6,
      },
      {
        key: "annealingSetup",
        label: "Annealing Setup",
        type: "select",
        required: false,
        options: ["None", "Torch (manual)", "AMP Annealer", "Induction (other)", "Flame-based (automated)"],
        wide: false,
        order: 7,
      },
    ],

    pipelineSteps: [
      pipelineStep("Brass Prep", 0, { color: "gray" }),
      pipelineStep("Sizing", 1, { color: "blue" }),
      pipelineStep("Priming", 2, { color: "cyan" }),
      pipelineStep("Charging", 3, { color: "amber" }),
      pipelineStep("Bullet Seating", 4, { color: "teal" }),
      pipelineStep("QC & Measurement", 5, { color: "green" }),
      pipelineStep("Range Testing", 6, { color: "blue" }),
      pipelineStep("Completed", 7, { color: "green", isFinal: true }),
    ],

    metricTemplates: [
      hobbyMetric({
        key: "muzzle-velocity-avg",
        name: "Muzzle Velocity (Avg)",
        unit: "fps",
        description: "Average muzzle velocity from chronograph data",
      }),
      hobbyMetric({
        key: "muzzle-velocity-sd",
        name: "Velocity Std Dev (SD)",
        unit: "fps",
        description: "Standard deviation of muzzle velocity — lower is more consistent",
      }),
      hobbyMetric({
        key: "muzzle-velocity-es",
        name: "Velocity Extreme Spread (ES)",
        unit: "fps",
        description: "Difference between fastest and slowest rounds in a string",
      }),
      hobbyMetric({
        key: "group-size",
        name: "Group Size",
        unit: "MOA",
        description: "Best group size at tested distance",
      }),
      hobbyMetric({
        key: "group-distance",
        name: "Group Test Distance",
        unit: "yd",
        description: "Distance at which groups were measured",
      }),
      hobbyMetric({
        key: "coal-measured",
        name: "COAL (Measured)",
        unit: "in",
        description: "Actual cartridge overall length measured after seating",
      }),
      hobbyMetric({
        key: "cbto-measured",
        name: "CBTO (Measured)",
        unit: "in",
        description: "Cartridge base to ogive measurement",
      }),
      hobbyMetric({
        key: "runout",
        name: "Concentricity / Runout",
        unit: "in",
        description: "TIR at bullet ogive — indicates bullet-to-case alignment",
      }),
      hobbyMetric({
        key: "powder-charge-actual",
        name: "Powder Charge (Actual)",
        unit: "gr",
        description: "Actual dispensed powder charge weight",
      }),
      hobbyMetric({
        key: "primer-seating-depth",
        name: "Primer Seating Depth",
        unit: "in",
        description: "Depth below flush — typically 0.003-0.005 below case head",
      }),
      hobbyMetric({
        key: "case-trim-length",
        name: "Case Trim Length",
        unit: "in",
        description: "Case length after trimming",
      }),
      hobbyMetric({
        key: "rounds-produced",
        name: "Rounds Produced",
        unit: "rds",
        description: "Number of completed rounds in this session",
      }),
    ],

    inventoryCategories: [
      "Brass — Rifle",
      "Brass — Pistol",
      "Brass — Shotshell",
      "Primers — Small Rifle",
      "Primers — Large Rifle",
      "Primers — Small Pistol",
      "Primers — Large Pistol",
      "Primers — Shotshell",
      "Powder — Rifle",
      "Powder — Pistol",
      "Powder — Shotshell",
      "Projectiles — Rifle",
      "Projectiles — Pistol",
      "Wads & Hulls",
      "Cleaning & Lube",
      "Dies & Tooling",
    ],

    recipeFields: [
      recipeField({
        key: "cartridge",
        label: "Cartridge",
        type: "string",
        helpText: "e.g., 6.5 Creedmoor, .308 Winchester, .223 Remington, 9mm Luger",
        group: "Cartridge",
      }),
      recipeField({
        key: "cartridgeType",
        label: "Cartridge Type",
        type: "select",
        options: ["Rifle", "Pistol", "Shotshell"],
        group: "Cartridge",
      }),
      recipeField({
        key: "brassManufacturer",
        label: "Brass Manufacturer",
        type: "string",
        helpText: "e.g., Lapua, Starline, Peterson, Federal (once-fired)",
        group: "Brass",
      }),
      recipeField({
        key: "brassFirings",
        label: "Brass Firings",
        type: "number",
        helpText: "Number of times this brass has been fired, including this load",
        group: "Brass",
      }),
      recipeField({
        key: "brassPrep",
        label: "Brass Prep Notes",
        type: "string",
        helpText: "e.g., FL sized, bumped -0.002, trimmed to 1.750, annealed",
        group: "Brass",
      }),
      recipeField({
        key: "primerType",
        label: "Primer",
        type: "string",
        helpText: "e.g., CCI BR2, Federal 210M, Winchester WSR",
        group: "Primer",
      }),
      recipeField({
        key: "powderType",
        label: "Powder",
        type: "string",
        helpText: "e.g., Hodgdon H4350, Varget, Alliant Reloder 16",
        group: "Powder",
      }),
      recipeField({
        key: "powderCharge",
        label: "Powder Charge",
        type: "number",
        unit: "gr",
        helpText: "Charge weight in grains. ALWAYS cross-reference published load data.",
        group: "Powder",
      }),
      recipeField({
        key: "powderLotNumber",
        label: "Powder Lot Number",
        type: "string",
        helpText: "Lot-to-lot variation can shift velocity 20-50 fps",
        group: "Powder",
      }),
      recipeField({
        key: "bulletManufacturer",
        label: "Bullet Manufacturer",
        type: "string",
        helpText: "e.g., Sierra, Berger, Hornady, Nosler",
        group: "Bullet",
      }),
      recipeField({
        key: "bulletName",
        label: "Bullet Name",
        type: "string",
        helpText: "e.g., 140gr Berger Hybrid Target, 168gr Sierra MatchKing",
        group: "Bullet",
      }),
      recipeField({ key: "bulletWeight", label: "Bullet Weight", type: "number", unit: "gr", group: "Bullet" }),
      recipeField({
        key: "bulletType",
        label: "Bullet Type",
        type: "select",
        options: [
          "FMJ",
          "BTHP (Match)",
          "Hybrid (Match)",
          "Polymer Tip",
          "Soft Point",
          "Bonded",
          "Monolithic (Solid Copper)",
          "Lead Round Nose",
          "JHP",
          "Partition",
          "AccuBond",
        ],
        group: "Bullet",
      }),
      recipeField({
        key: "bulletBC",
        label: "Bullet BC (G7)",
        type: "number",
        helpText: "G7 ballistic coefficient — preferred for long-range. Use G1 if G7 is not published.",
        group: "Bullet",
      }),
      recipeField({
        key: "targetCOAL",
        label: "Target COAL",
        type: "number",
        unit: "in",
        helpText: "Cartridge overall length, tip of bullet to base of case",
        group: "Seating",
      }),
      recipeField({
        key: "targetCBTO",
        label: "Target CBTO",
        type: "number",
        unit: "in",
        helpText: "Cartridge base to ogive — more repeatable than COAL for tipped bullets",
        group: "Seating",
      }),
      recipeField({
        key: "jumpToLands",
        label: "Jump to Lands",
        type: "number",
        unit: "in",
        helpText: "Distance from bullet ogive to rifling lands, e.g., 0.020",
        group: "Seating",
      }),
      recipeField({
        key: "crimpType",
        label: "Crimp",
        type: "select",
        options: ["None", "Light Taper", "Factory Taper", "Roll Crimp", "Heavy Crimp"],
        group: "Seating",
      }),
      recipeField({
        key: "expectedVelocity",
        label: "Expected Velocity",
        type: "number",
        unit: "fps",
        helpText: "Predicted MV from load manual or QuickLOAD",
        group: "Ballistics",
      }),
      recipeField({
        key: "maxPressure",
        label: "Max Pressure (SAAMI)",
        type: "number",
        unit: "psi",
        helpText: "SAAMI maximum average pressure for this cartridge",
        group: "Safety",
      }),
      recipeField({
        key: "loadDataSource",
        label: "Load Data Source",
        type: "string",
        helpText: "e.g., Hodgdon online, Sierra 6th Ed, Berger manual, personal workup",
        group: "Safety",
      }),
      recipeField({
        key: "loadClassification",
        label: "Load Classification",
        type: "select",
        options: ["Starting Load", "Mid-Range", "Near Max", "Max Published", "Over Max — USE CAUTION"],
        group: "Safety",
      }),
    ],

    suggestedEquipment: [
      "Reloading Press",
      "Die Set",
      "Powder Scale",
      "Powder Measure / Dispenser",
      "Priming Tool",
      "Case Trimmer",
      "Chamfer / Deburr Tool",
      "Caliper (digital)",
      "COAL / CBTO Gauge",
      "Bullet Comparator",
      "Concentricity Gauge",
      "Case Tumbler / Ultrasonic Cleaner",
      "Case Lube",
      "Funnel / Powder Trickler",
      "Loading Block / Tray",
      "Chronograph",
      "Bullet Puller (kinetic)",
      "Primer Pocket Uniformer",
      "Flash Hole Deburr Tool",
      "Annealer",
      "Torque Wrench (action screws)",
    ],

    sessionStepTypes: [
      "deprime",
      "clean",
      "inspect",
      "trim",
      "chamfer-deburr",
      "size",
      "anneal",
      "prime",
      "charge",
      "seat",
      "crimp",
      "measure",
      "qc-check",
      "range-test",
      "log-data",
    ],

    starterRecipes: [
      {
        name: "6.5 Creedmoor — 140gr Berger Hybrid Target",
        description: "A proven precision rifle load for 6.5 Creedmoor. Mid-range charge of H4350 behind the 140gr Berger Hybrid. Widely used in PRS and F-Class competition.",
        styleCategory: "Precision Rifle",
        ingredients: [
          {
            name: "Lapua 6.5 Creedmoor Brass",
            quantity: 50,
            unit: "pcs",
            category: "Brass — Rifle",
            notes: "New or once-fired, FL sized, trimmed to 1.910",
          },
          {
            name: "CCI BR2 Large Rifle Primers",
            quantity: 50,
            unit: "pcs",
            category: "Primers — Large Rifle",
            notes: "Bench rest grade for consistency",
          },
          {
            name: "Hodgdon H4350 Powder",
            quantity: 2100,
            unit: "gr",
            category: "Powder — Rifle",
            notes: "42.0 gr per round × 50 rounds",
          },
          {
            name: "Berger 140gr Hybrid Target",
            quantity: 50,
            unit: "pcs",
            category: "Projectiles — Rifle",
            notes: "Lot-sorted by bearing surface if possible",
          },
          {
            name: "Imperial Sizing Die Wax",
            quantity: 1,
            unit: "application",
            category: "Cleaning & Lube",
            notes: "Light application before sizing",
          },
        ],
        steps: [
          {
            title: "Inspect Brass",
            description: "Visually inspect all brass for cracks at the neck and case head. Check primer pockets for looseness. Discard any suspect cases. If brass is once-fired, note the number of firings.",
            stepType: "inspect",
            durationMinutes: 15,
          },
          {
            title: "Clean Brass",
            description: "Tumble in walnut media or ultrasonic clean. Brass should be free of carbon and debris. Dry completely before proceeding.",
            stepType: "clean",
            durationMinutes: 60,
          },
          {
            title: "Lube and Full-Length Size",
            description: "Apply sizing wax lightly to case body. Full-length size with bushing die or standard FL die. Target shoulder bump of 0.001-0.002 from fired dimension.",
            stepType: "size",
            durationMinutes: 30,
          },
          {
            title: "Trim to Length",
            description: "Trim all cases to 1.910 inches. Chamfer the inside of the case mouth and deburr the outside. Uniform primer pockets if desired.",
            stepType: "trim",
            durationMinutes: 30,
          },
          {
            title: "Anneal Necks",
            description: "Anneal case necks to restore consistent neck tension. Use appropriate annealing setup for your equipment. Skip if brass is new or has fewer than 3 firings.",
            stepType: "anneal",
            durationMinutes: 20,
          },
          {
            title: "Prime Cases",
            description: "Seat CCI BR2 primers to 0.003-0.005 below flush. Primers should seat with firm, consistent resistance. Any primer that seats with no resistance indicates a loose pocket — discard that case.",
            stepType: "prime",
            durationMinutes: 15,
          },
          {
            title: "Charge with Powder",
            description: "Dispense 42.0 grains H4350 per case. Verify every charge on the scale. Use a powder trickler for the last few tenths of a grain. Visually inspect all charged cases under light to confirm consistent fill levels before seating bullets.",
            stepType: "charge",
            durationMinutes: 30,
          },
          {
            title: "Seat Bullets",
            description: "Seat 140gr Berger Hybrid Target to COAL 2.800 / CBTO per your rifle's measured lands minus desired jump (typically 0.010-0.030 off the lands). Adjust seating die in small increments and verify first 3 rounds with calipers.",
            stepType: "seat",
            durationMinutes: 20,
          },
          {
            title: "QC — Measure and Sort",
            description: "Measure COAL and CBTO on every round. Check concentricity/runout on a sample — target under 0.002 TIR. Weight-sort completed rounds if doing load development — variation should be under 0.5 gr.",
            stepType: "qc-check",
            durationMinutes: 20,
          },
          {
            title: "Range Test",
            description: "Shoot 5-round groups at 100 yards minimum. Record chronograph data for every round. Inspect fired brass for pressure signs: flattened primers, ejector marks, shiny case heads. Log group sizes.",
            stepType: "range-test",
            durationMinutes: undefined,
          },
          {
            title: "Log Results",
            description: "Record velocity average, SD, ES, and group sizes. Note any anomalies — flyers, feeding issues, extraction feel. If load shows promise (SD under 10, groups under 0.75 MOA), mark recipe as proven. If not, adjust charge weight in 0.3 gr increments and re-test.",
            stepType: "log-data",
            durationMinutes: 15,
          },
        ],
        customFields: {
          cartridge: "6.5 Creedmoor",
          cartridgeType: "Rifle",
          brassManufacturer: "Lapua",
          brassFirings: 1,
          brassPrep: "FL sized, bumped -0.002, trimmed 1.910, pockets uniformed",
          primerType: "CCI BR2",
          powderType: "Hodgdon H4350",
          powderCharge: 42.0,
          bulletManufacturer: "Berger",
          bulletName: "140gr Hybrid Target",
          bulletWeight: 140,
          bulletType: "Hybrid (Match)",
          bulletBC: 0.311,
          targetCOAL: 2.8,
          jumpToLands: 0.02,
          crimpType: "None",
          expectedVelocity: 2750,
          maxPressure: 62000,
          loadDataSource: "Hodgdon online data center",
          loadClassification: "Mid-Range",
        },
      },
      {
        name: "9mm Luger — 124gr FMJ Plinking Load",
        description: "Economical high-volume 9mm load for practice and competition. Moderate power factor, reliable feeding across platforms.",
        styleCategory: "Pistol — Practice",
        ingredients: [
          {
            name: "9mm Luger Brass (mixed)",
            quantity: 200,
            unit: "pcs",
            category: "Brass — Pistol",
            notes: "Range pickup brass, sorted and cleaned",
          },
          {
            name: "Winchester WSP Small Pistol Primers",
            quantity: 200,
            unit: "pcs",
            category: "Primers — Small Pistol",
          },
          {
            name: "Hodgdon Titegroup Powder",
            quantity: 820,
            unit: "gr",
            category: "Powder — Pistol",
            notes: "4.1 gr per round × 200 rounds",
          },
          {
            name: "Berry's 124gr FMJ RN Projectiles",
            quantity: 200,
            unit: "pcs",
            category: "Projectiles — Pistol",
            notes: "Plated — do not exceed plated bullet max velocities",
          },
        ],
        steps: [
          {
            title: "Sort and Inspect Brass",
            description: "Sort brass by headstamp if desired (not critical for practice ammo). Inspect for cracks, splits, and Berdan-primed cases (discard). 9mm brass is cheap — reject anything questionable.",
            stepType: "inspect",
            durationMinutes: 15,
          },
          {
            title: "Clean Brass",
            description: "Tumble or ultrasonic clean. 9mm picks up a lot of range grime. Dry thoroughly — wet primers are dead primers.",
            stepType: "clean",
            durationMinutes: 45,
          },
          {
            title: "Size and Deprime",
            description: "Run all cases through the carbide sizing die. 9mm carbide dies do not require case lube. Inspect the expander ball for smooth operation. Flared case mouths from the previous firing get straightened here.",
            stepType: "size",
            durationMinutes: 20,
          },
          {
            title: "Prime Cases",
            description: "Seat WSP primers. Small pistol pockets are tight on new brass and loose on high-fire-count brass. Discard any case where the primer drops in with no resistance.",
            stepType: "prime",
            durationMinutes: 15,
          },
          {
            title: "Charge with Powder",
            description: "Dispense 4.1 grains Titegroup per case. Titegroup is a fast powder with small charge weights — double charges are possible and catastrophically dangerous. Visually inspect EVERY case under a light before seating bullets. A double charge will be visibly obvious at this charge weight.",
            stepType: "charge",
            durationMinutes: 25,
          },
          {
            title: "Seat Bullets and Taper Crimp",
            description: "Seat Berry's 124gr RN to 1.150 COAL. Apply light taper crimp — remove the case mouth bell only. Do not roll crimp on 9mm. Verify COAL on the first 5 rounds.",
            stepType: "seat",
            durationMinutes: 25,
          },
          {
            title: "Gauge Check",
            description: "Drop-test a sample of 10 rounds in a case gauge or the barrel of your pistol (removed from the gun). Every round should drop in and spin freely. Rounds that hang up have sizing or seating issues — pull and rework.",
            stepType: "qc-check",
            durationMinutes: 10,
          },
          {
            title: "Function Test",
            description: "Shoot a magazine's worth through your primary pistol to confirm feeding, extraction, and ejection. Note any failures. Check for keyholing at the target (indicates bullet instability). If everything runs clean, the batch is good.",
            stepType: "range-test",
            durationMinutes: undefined,
          },
        ],
        customFields: {
          cartridge: "9mm Luger",
          cartridgeType: "Pistol",
          brassManufacturer: "Mixed range brass",
          brassFirings: 0,
          brassPrep: "Sized in carbide die, no trim needed",
          primerType: "Winchester WSP",
          powderType: "Hodgdon Titegroup",
          powderCharge: 4.1,
          bulletManufacturer: "Berry's",
          bulletName: "124gr FMJ Round Nose (plated)",
          bulletWeight: 124,
          bulletType: "FMJ",
          targetCOAL: 1.15,
          crimpType: "Light Taper",
          expectedVelocity: 1100,
          maxPressure: 35000,
          loadDataSource: "Hodgdon online data center",
          loadClassification: "Mid-Range",
        },
      },
    ],
  }),
  hobbyPreset({
    key: "woodworking",
    label: "Woodworking",
    description: "Furniture, cabinetry, turning, carving, and shop projects — design templates, lumber tracking, build logs, and finishing records.",
    lifecycleMode: "pipeline",
    tags: ["woodworking", "furniture", "carpentry", "turning", "carving", "maker", "shop"],

    suggestedCustomFields: [
      {
        key: "shopType",
        label: "Shop Type",
        type: "select",
        required: false,
        options: ["Garage Shop", "Dedicated Shop", "Basement Shop", "Outdoor / Covered", "Shared / Makerspace"],
        wide: false,
        order: 0,
      },
      {
        key: "primaryDiscipline",
        label: "Primary Discipline",
        type: "select",
        required: false,
        options: [
          "Furniture",
          "Cabinetry",
          "Turning (Lathe)",
          "Carving",
          "Scroll Saw / Fretwork",
          "General / Mixed",
          "Luthier (Instruments)",
          "Boat Building",
        ],
        wide: false,
        order: 1,
      },
      {
        key: "dustCollection",
        label: "Dust Collection",
        type: "select",
        required: false,
        options: ["None", "Shop Vac", "Single-Stage Collector", "Two-Stage Collector", "Cyclone System"],
        wide: false,
        order: 2,
      },
      {
        key: "primaryWoodSpecies",
        label: "Primary Wood Species",
        type: "string",
        required: false,
        options: [],
        wide: false,
        order: 3,
        helpText: "e.g., Walnut, Cherry, Maple, Oak",
      },
      {
        key: "preferredJoinery",
        label: "Preferred Joinery",
        type: "select",
        required: false,
        options: ["Pocket Screws", "Dowels", "Biscuits", "Dominos (Festool)", "Mortise & Tenon", "Dovetails", "Box Joints", "Mixed / Hand-Cut"],
        wide: false,
        order: 4,
      },
      {
        key: "finishingSpace",
        label: "Dedicated Finishing Space",
        type: "select",
        required: false,
        options: ["Yes — Separate Room", "Yes — Spray Booth", "Same as Shop", "Outdoor Only", "No"],
        wide: false,
        order: 5,
      },
      {
        key: "latheSize",
        label: "Lathe Swing / Size",
        type: "string",
        required: false,
        options: [],
        wide: false,
        order: 6,
        helpText: "e.g., 12x36 midi lathe, 16x42 full size",
      },
      {
        key: "tablesaw",
        label: "Table Saw Type",
        type: "select",
        required: false,
        options: ["None", "Jobsite / Portable", "Contractor", "Hybrid", "Cabinet Saw"],
        wide: false,
        order: 7,
      },
    ],

    pipelineSteps: [
      pipelineStep("Design & Planning", 0, { color: "gray" }),
      pipelineStep("Material Selection", 1, { color: "blue" }),
      pipelineStep("Milling & Dimensioning", 2, { color: "cyan" }),
      pipelineStep("Joinery", 3, { color: "amber" }),
      pipelineStep("Assembly & Glue-Up", 4, { color: "teal" }),
      pipelineStep("Shaping & Detailing", 5, { color: "blue" }),
      pipelineStep("Surface Prep", 6, { color: "cyan" }),
      pipelineStep("Finishing", 7, { color: "amber" }),
      pipelineStep("Final Assembly & Hardware", 8, { color: "teal" }),
      pipelineStep("Completed", 9, { color: "green", isFinal: true }),
    ],

    metricTemplates: [
      hobbyMetric({
        key: "lumber-cost",
        name: "Lumber Cost",
        unit: "$",
        description: "Total cost of lumber used in this build",
      }),
      hobbyMetric({
        key: "hardware-cost",
        name: "Hardware Cost",
        unit: "$",
        description: "Cost of hinges, screws, pulls, slides, and other hardware",
      }),
      hobbyMetric({
        key: "finish-cost",
        name: "Finishing Supplies Cost",
        unit: "$",
        description: "Cost of stains, finishes, sandpaper, and related supplies",
      }),
      hobbyMetric({
        key: "total-build-hours",
        name: "Total Build Hours",
        unit: "hrs",
        description: "Total shop time from first cut to final coat",
      }),
      hobbyMetric({
        key: "board-feet-used",
        name: "Board Feet Used",
        unit: "bf",
        description: "Total board feet of lumber consumed",
      }),
      hobbyMetric({
        key: "waste-percentage",
        name: "Waste Percentage",
        unit: "%",
        description: "Estimated material waste — offcuts, defect removal, mistakes",
      }),
      hobbyMetric({
        key: "finish-coats",
        name: "Finish Coats Applied",
        unit: "coats",
        description: "Number of finish coats applied",
      }),
      hobbyMetric({
        key: "moisture-content",
        name: "Moisture Content",
        unit: "%",
        description: "Lumber moisture content at time of milling — target 6-8% for interior furniture",
      }),
      hobbyMetric({
        key: "final-dimensions-length",
        name: "Final Dimensions — Length",
        unit: "in",
        description: "Finished piece length",
      }),
      hobbyMetric({
        key: "final-dimensions-width",
        name: "Final Dimensions — Width",
        unit: "in",
        description: "Finished piece width",
      }),
      hobbyMetric({
        key: "final-dimensions-height",
        name: "Final Dimensions — Height",
        unit: "in",
        description: "Finished piece height or depth",
      }),
      hobbyMetric({
        key: "difficulty-rating",
        name: "Difficulty Rating",
        unit: "1-5",
        description: "Self-assessed project difficulty — 1 easy, 5 very challenging",
      }),
    ],

    inventoryCategories: [
      "Hardwood Lumber",
      "Softwood Lumber",
      "Plywood & Sheet Goods",
      "Exotic / Specialty Wood",
      "Turning Blanks & Spindle Stock",
      "Veneer & Edgebanding",
      "Hardware — Hinges & Slides",
      "Hardware — Knobs & Pulls",
      "Hardware — Screws & Fasteners",
      "Hardware — Knock-Down / Specialty",
      "Adhesives & Glue",
      "Sandpaper & Abrasives",
      "Stains & Dyes",
      "Film Finishes (Poly, Lacquer, Shellac)",
      "Oil Finishes (Tung, Danish, BLO)",
      "Saw Blades & Router Bits",
    ],

    recipeFields: [
      recipeField({
        key: "projectType",
        label: "Project Type",
        type: "select",
        options: [
          "Furniture",
          "Cabinet / Case",
          "Box / Small Container",
          "Cutting Board / Butcher Block",
          "Turned Item (Bowl, Vessel)",
          "Turned Item (Spindle, Pen)",
          "Wall Art / Decor",
          "Toy / Game",
          "Jig / Shop Fixture",
          "Outdoor / Garden",
          "Instrument",
          "Other",
        ],
        group: "Design",
      }),
      recipeField({
        key: "primarySpecies",
        label: "Primary Wood Species",
        type: "string",
        helpText: "e.g., Black Walnut, Hard Maple, White Oak",
        group: "Materials",
      }),
      recipeField({
        key: "secondarySpecies",
        label: "Secondary / Accent Species",
        type: "string",
        helpText: "Contrasting wood for accents, inlays, or edge banding",
        group: "Materials",
      }),
      recipeField({
        key: "roughLumberBF",
        label: "Rough Lumber Needed",
        type: "number",
        unit: "bf",
        helpText: "Board feet of rough lumber before milling — include 20-30% waste factor",
        group: "Materials",
      }),
      recipeField({
        key: "thickness",
        label: "Final Stock Thickness",
        type: "string",
        helpText: "e.g., 3/4 inch, 4/4 rough to 13/16 finished",
        group: "Materials",
      }),
      recipeField({
        key: "sheetGoodsNeeded",
        label: "Sheet Goods Needed",
        type: "string",
        helpText: "e.g., 1 sheet 3/4 Baltic Birch ply",
        group: "Materials",
      }),
      recipeField({
        key: "primaryJoinery",
        label: "Primary Joinery Method",
        type: "select",
        options: [
          "Butt Joints",
          "Pocket Screws",
          "Dowels",
          "Biscuits",
          "Dominos",
          "Mortise & Tenon",
          "Through Dovetails",
          "Half-Blind Dovetails",
          "Box / Finger Joints",
          "Dado & Rabbet",
          "Bridle Joint",
          "Lap Joint",
          "Miter (reinforced)",
          "Miter (splined)",
        ],
        group: "Joinery",
      }),
      recipeField({
        key: "secondaryJoinery",
        label: "Secondary Joinery",
        type: "string",
        helpText: "Any additional joint types used in this design",
        group: "Joinery",
      }),
      recipeField({
        key: "finishType",
        label: "Finish Type",
        type: "select",
        options: [
          "Polyurethane (oil-based)",
          "Polyurethane (water-based)",
          "Lacquer (spray)",
          "Shellac",
          "Danish Oil",
          "Tung Oil",
          "Boiled Linseed Oil",
          "Wipe-On Poly",
          "Arm-R-Seal",
          "Milk Paint",
          "Chalk Paint + Wax",
          "Epoxy / Resin",
          "Food-Safe Oil (mineral oil / beeswax)",
          "None / Raw",
          "Other",
        ],
        group: "Finishing",
      }),
      recipeField({
        key: "finishCoatsPlanned",
        label: "Planned Finish Coats",
        type: "number",
        helpText: "Total coats including sealer",
        group: "Finishing",
      }),
      recipeField({
        key: "sandingProgression",
        label: "Sanding Progression",
        type: "string",
        helpText: "e.g., 80 → 120 → 180 → 220, or 120 → 180 → raise grain → 220",
        group: "Finishing",
      }),
      recipeField({ key: "finishedLength", label: "Finished Length", type: "number", unit: "in", group: "Dimensions" }),
      recipeField({ key: "finishedWidth", label: "Finished Width", type: "number", unit: "in", group: "Dimensions" }),
      recipeField({ key: "finishedHeight", label: "Finished Height / Depth", type: "number", unit: "in", group: "Dimensions" }),
      recipeField({
        key: "designSource",
        label: "Design Source",
        type: "select",
        options: [
          "Original Design",
          "Published Plan (book/magazine)",
          "Online Plan (free)",
          "Online Plan (paid)",
          "YouTube Build-Along",
          "Class / Workshop",
          "Customer Commission",
          "Adaptation / Modified Plan",
        ],
        group: "Source",
      }),
      recipeField({
        key: "designUrl",
        label: "Design URL / Reference",
        type: "string",
        helpText: "Link to plan source, SketchUp file, or reference photo",
        group: "Source",
      }),
      recipeField({ key: "estimatedBuildHours", label: "Estimated Build Hours", type: "number", unit: "hrs", group: "Estimates" }),
      recipeField({ key: "estimatedMaterialCost", label: "Estimated Material Cost", type: "number", unit: "$", group: "Estimates" }),
      recipeField({
        key: "skillLevel",
        label: "Skill Level",
        type: "select",
        options: ["Beginner", "Intermediate", "Advanced", "Expert"],
        group: "Design",
      }),
    ],

    suggestedEquipment: [
      "Table Saw",
      "Miter Saw",
      "Band Saw",
      "Jointer",
      "Thickness Planer",
      "Router Table",
      "Handheld Router",
      "Drill Press",
      "Random Orbit Sander",
      "Belt Sander",
      "Oscillating Spindle Sander",
      "Lathe",
      "Scroll Saw",
      "Hand Planes (bench set)",
      "Chisels (bench set)",
      "Dovetail Saw",
      "Marking Gauge",
      "Combination Square",
      "Moisture Meter",
      "Digital Calipers",
      "Clamps (bar, pipe, parallel)",
      "Workbench with Vises",
      "Dust Collector",
      "Spray Gun / HVLP",
    ],

    sessionStepTypes: [
      "design",
      "select-material",
      "rough-cut",
      "joint",
      "plane",
      "rip",
      "crosscut",
      "template",
      "cut-joinery",
      "dry-fit",
      "glue-up",
      "clamp",
      "shape",
      "route",
      "carve",
      "turn",
      "inlay",
      "sand",
      "scrape",
      "stain",
      "seal",
      "finish-coat",
      "rub-out",
      "install-hardware",
      "assemble",
      "inspect",
    ],

    starterRecipes: [
      {
        name: "End-Grain Cutting Board — Walnut & Maple",
        description: "Classic end-grain cutting board with alternating walnut and maple strips. Approximately 12×18 inches. A great intermediate project that practices glue-ups, planing, and food-safe finishing.",
        styleCategory: "Cutting Board / Butcher Block",
        ingredients: [
          {
            name: "Black Walnut (4/4 rough)",
            quantity: 3,
            unit: "bf",
            category: "Hardwood Lumber",
            notes: "Select for straight grain, minimal sapwood",
          },
          {
            name: "Hard Maple (4/4 rough)",
            quantity: 3,
            unit: "bf",
            category: "Hardwood Lumber",
            notes: "Avoid figured stock — flat grain glues more reliably for end-grain",
          },
          {
            name: "Titebond III Wood Glue",
            quantity: 8,
            unit: "oz",
            category: "Adhesives & Glue",
            notes: "Waterproof — required for cutting boards",
          },
          {
            name: "Mineral Oil",
            quantity: 4,
            unit: "oz",
            category: "Oil Finishes (Tung, Danish, BLO)",
            notes: "Food-safe, for initial treatment",
          },
          {
            name: "Board Butter (mineral oil + beeswax)",
            quantity: 2,
            unit: "oz",
            category: "Oil Finishes (Tung, Danish, BLO)",
            notes: "Final coat — provides mild water resistance",
          },
          {
            name: "Sandpaper Assorted (120, 150, 180, 220)",
            quantity: 4,
            unit: "sheets",
            category: "Sandpaper & Abrasives",
          },
          {
            name: "Rubber Bumper Feet",
            quantity: 4,
            unit: "pcs",
            category: "Hardware — Knock-Down / Specialty",
            notes: "Self-adhesive, prevent sliding and allow airflow under the board",
          },
        ],
        steps: [
          {
            title: "Mill Lumber to Thickness",
            description: "Joint one face and one edge of each board. Plane to 1.5 inches thick (final board will be 1.5 inches tall). Let acclimate overnight after milling if boards were recently surfaced.",
            stepType: "plane",
            durationMinutes: 30,
          },
          {
            title: "Rip Strips",
            description: "Rip walnut and maple into 1.5-inch wide strips at the table saw. Use a push stick and featherboard. You need approximately 6 strips of each species for a 12×18 board.",
            stepType: "rip",
            durationMinutes: 20,
          },
          {
            title: "First Glue-Up (Face Grain Panel)",
            description: "Arrange strips in alternating walnut-maple pattern. Glue and clamp face-to-face into a panel. Use cauls to keep the panel flat. Check for squeeze-out and wipe excess with a damp rag. Let cure 2-4 hours minimum.",
            stepType: "glue-up",
            durationMinutes: 30,
          },
          {
            title: "Flatten and Crosscut",
            description: "Run the panel through the planer (take very light passes — this is face grain going through cross-grain, so tear-out risk is high). Alternatively, flatten with a hand plane or router sled. Once flat, crosscut the panel into 1.5-inch strips on the miter saw or crosscut sled.",
            stepType: "crosscut",
            durationMinutes: 30,
          },
          {
            title: "Second Glue-Up (End Grain Up)",
            description: "Rotate the strips 90 degrees so the end grain faces up. Arrange in your desired pattern — you can offset strips for a brick pattern or keep them aligned for a checkerboard. Glue and clamp. This glue-up is trickier because end-grain strips want to slide. Use a flat caul and hand pressure. Cure 4+ hours.",
            stepType: "glue-up",
            durationMinutes: 30,
          },
          {
            title: "Flatten End Grain",
            description: "Do NOT run end grain through a thickness planer — it will explode. Flatten with a router sled, drum sander, or hand plane (very sharp blade, light cuts). Work to final thickness of approximately 1.25-1.5 inches.",
            stepType: "sand",
            durationMinutes: 45,
          },
          {
            title: "Shape and Ease Edges",
            description: "Square up the edges on the table saw if needed. Round over all edges with a 1/8-inch roundover bit in the router or ease by hand with sandpaper. This prevents chipping and feels better in use.",
            stepType: "route",
            durationMinutes: 15,
          },
          {
            title: "Sand Through Grits",
            description: "Sand the top and bottom faces: 120 → 150 → 180 → 220. Between 180 and 220, wipe with a damp cloth to raise the grain, let dry, then sand with 220. This prevents the grain from raising when the board gets wet in use.",
            stepType: "sand",
            durationMinutes: 30,
          },
          {
            title: "Apply Mineral Oil",
            description: "Flood the board with food-grade mineral oil. Let it soak for 20 minutes, then wipe off excess. Repeat 3-4 times over 24 hours until the wood stops absorbing oil. Let dry 24 hours.",
            stepType: "finish-coat",
            durationMinutes: 30,
          },
          {
            title: "Apply Board Butter & Final Touches",
            description: "Apply board butter (mineral oil + beeswax blend) to all surfaces. Buff with a clean cloth. Attach rubber bumper feet to the bottom corners. The board is ready to use.",
            stepType: "finish-coat",
            durationMinutes: 15,
          },
        ],
        customFields: {
          projectType: "Cutting Board / Butcher Block",
          primarySpecies: "Black Walnut",
          secondarySpecies: "Hard Maple",
          roughLumberBF: 6,
          thickness: "4/4 rough to 1.5 inch, finished ~1.25-1.5 inch",
          primaryJoinery: "Butt Joints",
          finishType: "Food-Safe Oil (mineral oil / beeswax)",
          finishCoatsPlanned: 4,
          sandingProgression: "120 → 150 → 180 → raise grain → 220",
          finishedLength: 18,
          finishedWidth: 12,
          finishedHeight: 1.5,
          designSource: "Original Design",
          estimatedBuildHours: 6,
          estimatedMaterialCost: 45,
          skillLevel: "Intermediate",
        },
      },
      {
        name: "Dovetail Box — Cherry with Maple Lid",
        description: "Small hand-cut dovetail box in cherry with a floating maple panel lid. Approximately 8×5×4 inches. Focused on joinery practice — through dovetails at the corners, a grooved floating panel lid, and a simple rabbet for the plywood bottom.",
        styleCategory: "Box / Small Container",
        ingredients: [
          {
            name: "Cherry (4/4 rough)",
            quantity: 2,
            unit: "bf",
            category: "Hardwood Lumber",
            notes: "Straight grain, clear — avoid boards with heavy figure that makes hand-cutting dovetails harder",
          },
          {
            name: "Hard Maple (4/4 rough)",
            quantity: 0.5,
            unit: "bf",
            category: "Hardwood Lumber",
            notes: "For the floating lid panel",
          },
          {
            name: "Baltic Birch Plywood (1/4 inch)",
            quantity: 0.5,
            unit: "sqft",
            category: "Plywood & Sheet Goods",
            notes: "For the box bottom — rabbeted into the sides",
          },
          {
            name: "Titebond Original Wood Glue",
            quantity: 2,
            unit: "oz",
            category: "Adhesives & Glue",
          },
          {
            name: "Arm-R-Seal (satin)",
            quantity: 2,
            unit: "oz",
            category: "Film Finishes (Poly, Lacquer, Shellac)",
            notes: "Wipe-on oil-based polyurethane — 3 coats",
          },
          {
            name: "Sandpaper Assorted (120, 180, 220, 320)",
            quantity: 4,
            unit: "sheets",
            category: "Sandpaper & Abrasives",
          },
          {
            name: "Small Brass Hinges",
            quantity: 2,
            unit: "pcs",
            category: "Hardware — Hinges & Slides",
            notes: "Small butt hinges, mortised into the back",
          },
        ],
        steps: [
          {
            title: "Mill Stock to Thickness",
            description: "Joint and plane cherry to 3/8 inch for the box sides and maple to 3/8 inch for the lid panel. Rip cherry to 4 inches wide (box height) and crosscut to lengths: two at 8 inches (front/back), two at 5 inches (sides). Cut maple lid panel to fit inside a groove — final dimensions set after the box is assembled.",
            stepType: "plane",
            durationMinutes: 30,
          },
          {
            title: "Mark and Cut Dovetails",
            description: "Mark tails on the side pieces (the shorter boards). A small box like this typically uses 3 tails per corner. Use a dovetail marker at 1:8 ratio (hardwood). Saw tails with a dovetail saw, chop waste with a chisel. Transfer tails to pin boards, saw and chop pins. Test fit each corner.",
            stepType: "cut-joinery",
            durationMinutes: 120,
          },
          {
            title: "Cut Groove for Bottom",
            description: "Using a table saw or plow plane, cut a 1/4-inch groove on the inside of all four sides, 1/4 inch up from the bottom edge. This houses the plywood bottom panel. The groove must be positioned so it falls within a tail on the side pieces — do not let it emerge through a pin socket.",
            stepType: "route",
            durationMinutes: 15,
          },
          {
            title: "Cut Groove for Lid Panel",
            description: "On the front and two side pieces, cut a groove near the top inside edge to hold the floating maple lid panel. The back piece does NOT get this groove — the lid will be hinged to it instead.",
            stepType: "route",
            durationMinutes: 15,
          },
          {
            title: "Dry Fit and Cut Bottom Panel",
            description: "Dry-assemble the box with the plywood bottom in the groove. Verify all joints are tight, the box is square, and the bottom sits flat without bowing. Mark and cut the maple lid panel to fit the lid groove with 1/16 inch expansion gap on each side.",
            stepType: "dry-fit",
            durationMinutes: 20,
          },
          {
            title: "Glue-Up",
            description: "Glue the dovetails and assemble with bottom panel captured in the groove (do NOT glue the bottom panel — it must float). Check for square by measuring diagonals. Clamp lightly — dovetails should pull tight on their own. Clean squeeze-out from inside corners immediately with a damp brush.",
            stepType: "glue-up",
            durationMinutes: 30,
          },
          {
            title: "Separate Lid from Box",
            description: "Once the glue has cured, mark a line around all four sides at the lid height. Saw the lid off on the table saw (set fence to cut line, cut all four sides). Clean the saw marks with a hand plane or sandpaper on a flat surface.",
            stepType: "crosscut",
            durationMinutes: 20,
          },
          {
            title: "Fit Lid Panel and Hinges",
            description: "Slide the maple lid panel into the grooves on the lid frame. Mortise the back of the lid and back of the box for the small brass hinges. Install hinges with brass screws. Verify the lid opens smoothly and sits flat when closed.",
            stepType: "install-hardware",
            durationMinutes: 30,
          },
          {
            title: "Sand Through Grits",
            description: "Sand all exterior surfaces: 120 → 180 → 220. Lightly break all sharp edges by hand. Sand the lid panel separately before final assembly if you want to finish it differently.",
            stepType: "sand",
            durationMinutes: 30,
          },
          {
            title: "Apply Finish",
            description: "Apply 3 coats of Arm-R-Seal with a lint-free cloth. Sand lightly with 320 between coats after each coat cures (typically 24 hours). The final coat can be rubbed out with 0000 steel wool for a softer sheen.",
            stepType: "finish-coat",
            durationMinutes: 30,
          },
          {
            title: "Final Inspection",
            description: "Check all joints for gaps. Verify the lid opens and closes smoothly. Check the finish for drips, dust nibs, or uneven sheen. Apply a thin coat of paste wax if desired for a silky feel.",
            stepType: "inspect",
            durationMinutes: 10,
          },
        ],
        customFields: {
          projectType: "Box / Small Container",
          primarySpecies: "Cherry",
          secondarySpecies: "Hard Maple",
          roughLumberBF: 2.5,
          thickness: "4/4 rough to 3/8 inch",
          primaryJoinery: "Through Dovetails",
          secondaryJoinery: "Grooved floating panel (lid and bottom)",
          finishType: "Arm-R-Seal",
          finishCoatsPlanned: 3,
          sandingProgression: "120 → 180 → 220 → 320 between coats",
          finishedLength: 8,
          finishedWidth: 5,
          finishedHeight: 4,
          designSource: "Original Design",
          estimatedBuildHours: 10,
          estimatedMaterialCost: 35,
          skillLevel: "Advanced",
        },
      },
    ],
  }),
];
