-- AlterTable
ALTER TABLE "IdeaCanvas" ADD COLUMN     "backgroundImageUrl" VARCHAR(1000),
ADD COLUMN     "gridSize" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN     "physicalHeight" DOUBLE PRECISION,
ADD COLUMN     "physicalUnit" VARCHAR(10),
ADD COLUMN     "physicalWidth" DOUBLE PRECISION,
ADD COLUMN     "snapToGrid" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "IdeaCanvasNode" ADD COLUMN     "fillColor" VARCHAR(30),
ADD COLUMN     "objectType" VARCHAR(20) NOT NULL DEFAULT 'flowchart',
ADD COLUMN     "rotation" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "strokeColor" VARCHAR(30),
ADD COLUMN     "strokeWidth" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "x2" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "y2" DOUBLE PRECISION NOT NULL DEFAULT 0;
