import PDFDocument from "pdfkit";
import type { AssetTimelineItem } from "@lifekeeper/types";

type AssetHistoryPdfInput = {
  asset: {
    name: string;
    category: string;
    make?: string | null;
    model?: string | null;
    year?: number | null;
    assetTag?: string | null;
  };
  timelineItems: AssetTimelineItem[];
  costSummary: {
    lifetimeCost: number;
    yearToDateCost: number;
    rolling12MonthAverage: number;
    logCount: number;
  };
  dateRangeStart?: Date | null;
  dateRangeEnd?: Date | null;
};

const formatDate = (value: string | Date): string => new Intl.DateTimeFormat("en-US", {
  month: "short",
  day: "numeric",
  year: "numeric"
}).format(value instanceof Date ? value : new Date(value));

const formatDateTime = (value: Date): string => new Intl.DateTimeFormat("en-US", {
  month: "short",
  day: "numeric",
  year: "numeric",
  hour: "numeric",
  minute: "2-digit"
}).format(value);

const formatCurrency = (value: number): string => new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD"
}).format(value);

const formatTimelineSourceLabel = (sourceType: AssetTimelineItem["sourceType"]): string => {
  switch (sourceType) {
    case "maintenance_log":
      return "Maintenance Log";
    case "timeline_entry":
      return "Manual Entry";
    case "project_event":
      return "Project Event";
    case "inventory_transaction":
      return "Inventory Transaction";
    case "schedule_change":
      return "Schedule Change";
    case "comment":
      return "Comment";
    case "condition_assessment":
      return "Condition Assessment";
    case "usage_reading":
      return "Usage Reading";
    default:
      return "Activity";
  }
};

const truncate = (value: string, maxLength: number): string => value.length > maxLength
  ? `${value.slice(0, maxLength).trimEnd()}...`
  : value;

const writeRule = (doc: PDFKit.PDFDocument): void => {
  const y = doc.y;
  doc.save();
  doc.moveTo(doc.page.margins.left, y).lineTo(doc.page.width - doc.page.margins.right, y).strokeColor("#d7dde5").lineWidth(1).stroke();
  doc.restore();
  doc.moveDown(0.6);
};

const ensureSpace = (doc: PDFKit.PDFDocument, minimumRemaining: number): void => {
  const remaining = doc.page.height - doc.page.margins.bottom - doc.y;

  if (remaining < minimumRemaining) {
    doc.addPage();
  }
};

export const generateAssetHistoryPdf = (input: AssetHistoryPdfInput): PDFKit.PDFDocument => {
  const doc = new PDFDocument({ margin: 50, autoFirstPage: true });

  const rangeLabel = input.dateRangeStart || input.dateRangeEnd
    ? `${input.dateRangeStart ? formatDate(input.dateRangeStart) : "Beginning"} to ${input.dateRangeEnd ? formatDate(input.dateRangeEnd) : "Present"}`
    : "Complete History";
  const makeModelYear = [input.asset.year ?? null, input.asset.make ?? null, input.asset.model ?? null]
    .filter((part): part is string | number => part !== null && part !== undefined && String(part).trim().length > 0)
    .join(" ");

  doc.font("Helvetica-Bold").fontSize(24).text("Asset History Report", 50, 110, {
    align: "center"
  });
  doc.moveDown(0.6);
  doc.font("Helvetica").fontSize(18).text(input.asset.name, {
    align: "center"
  });
  doc.moveDown(2);

  doc.font("Helvetica-Bold").fontSize(12).text("Asset Details");
  doc.moveDown(0.5);
  doc.font("Helvetica").fontSize(11);
  if (makeModelYear) {
    doc.text(`Make / Model / Year: ${makeModelYear}`);
  }
  doc.text(`Asset Tag: ${input.asset.assetTag ?? "Not set"}`);
  doc.text(`Category: ${input.asset.category}`);
  doc.text(`Date Range: ${rangeLabel}`);

  doc.font("Helvetica").fontSize(10).text(
    `Generated ${formatDateTime(new Date())}\nGenerated by LifeKeeper`,
    50,
    doc.page.height - doc.page.margins.bottom - 40,
    { align: "left" }
  );

  doc.addPage();
  doc.font("Helvetica-Bold").fontSize(18).text("Timeline");
  doc.moveDown(0.8);

  for (const item of input.timelineItems) {
    ensureSpace(doc, 120);

    doc.font("Helvetica").fontSize(10).fillColor("#1f2937").text(formatDate(item.eventDate));
    doc.moveDown(0.2);
    doc.font("Helvetica-Bold").fontSize(9).fillColor("#374151").text(formatTimelineSourceLabel(item.sourceType));
    doc.moveDown(0.2);
    doc.font("Helvetica-Bold").fontSize(11).fillColor("#111827").text(item.title);

    if (item.description) {
      doc.moveDown(0.2);
      doc.font("Helvetica").fontSize(10).fillColor("#374151").text(truncate(item.description, 300));
    }

    if (typeof item.cost === "number") {
      doc.moveDown(0.2);
      doc.font("Helvetica").fontSize(10).fillColor("#111827").text(`Cost: ${formatCurrency(item.cost)}`);
    }

    if (item.parts && item.parts.length > 0) {
      doc.moveDown(0.3);
      for (const part of item.parts) {
        const partDetails = [
          part.name,
          part.partNumber ? `Part # ${part.partNumber}` : null,
          `Qty ${part.quantity}`,
          typeof part.unitCost === "number" ? formatCurrency(part.unitCost) : null
        ].filter((entry): entry is string => Boolean(entry)).join(" | ");

        doc.font("Helvetica").fontSize(8).fillColor("#4b5563").text(`  ${partDetails}`);
      }
    }

    doc.moveDown(0.5);
    writeRule(doc);
  }

  doc.addPage();
  doc.font("Helvetica-Bold").fontSize(18).fillColor("#111827").text("Cost Summary");
  doc.moveDown(1);

  const summaryRows: Array<[string, string]> = [
    ["Lifetime Cost", formatCurrency(input.costSummary.lifetimeCost)],
    ["Year-to-Date Cost", formatCurrency(input.costSummary.yearToDateCost)],
    ["Rolling 12-Month Average", formatCurrency(input.costSummary.rolling12MonthAverage)],
    ["Total Maintenance Logs", String(input.costSummary.logCount)]
  ];

  for (const [label, value] of summaryRows) {
    doc.font("Helvetica-Bold").fontSize(11).fillColor("#111827").text(label, { continued: true, width: 240 });
    doc.font("Helvetica").fontSize(11).fillColor("#374151").text(value);
    doc.moveDown(0.4);
    writeRule(doc);
  }

  return doc;
};