import cors from "@fastify/cors";
import Fastify from "fastify";
import { authPlugin } from "./plugins/auth.js";
import { errorHandlerPlugin } from "./plugins/error-handler.js";
import { prismaPlugin } from "./plugins/prisma.js";
import { storagePlugin } from "./plugins/storage.js";
import { assetRoutes } from "./routes/assets/index.js";
import { assetInventoryRoutes } from "./routes/assets/inventory.js";
import { timelineEntryRoutes } from "./routes/assets/timeline-entries.js";
import { timelineRoutes } from "./routes/assets/timeline.js";
import { assetTransferRoutes } from "./routes/assets/transfers.js";
import { dashboardRoutes } from "./routes/dashboard.js";
import { healthRoutes } from "./routes/health.js";
import { householdRoutes } from "./routes/households/index.js";
import { householdInventoryAnalyticsRoutes } from "./routes/households/inventory-analytics.js";
import { householdInventoryItemRoutes } from "./routes/households/inventory-items.js";
import { householdInventoryTransactionRoutes } from "./routes/households/inventory-transactions.js";
import { householdLinkPreviewRoutes } from "./routes/households/link-preview.js";
import { maintenanceLogRoutes } from "./routes/logs/index.js";
import { maintenanceLogPartRoutes } from "./routes/logs/parts.js";
import { meRoutes } from "./routes/me.js";
import { notificationRoutes } from "./routes/notifications/index.js";
import { presetRoutes } from "./routes/presets/index.js";
import { scheduleRoutes } from "./routes/schedules/index.js";
import { scheduleInventoryRoutes } from "./routes/schedules/inventory.js";
import { serviceProviderRoutes } from "./routes/service-providers/index.js";
import { usageMetricRoutes } from "./routes/usage-metrics/index.js";
import { usageMetricAnalyticsRoutes } from "./routes/usage-metrics/analytics.js";
import { activityLogRoutes } from "./routes/activity-logs/index.js";
import { complianceAnalyticsRoutes } from "./routes/analytics/compliance.js";
import { comparativeAnalyticsRoutes } from "./routes/analytics/comparative.js";
import { commentRoutes } from "./routes/comments/index.js";
import { costAnalyticsRoutes } from "./routes/cost-analytics/index.js";
import { exportRoutes } from "./routes/exports/index.js";
import { projectBudgetAnalyticsRoutes } from "./routes/cost-analytics/project-budget.js";
import { invitationRoutes } from "./routes/invitations/index.js";
import { projectRoutes } from "./routes/projects/index.js";
import { projectInventoryRoutes } from "./routes/projects/inventory.js";
import { projectNoteRoutes } from "./routes/projects/notes.js";
import { projectPhaseRoutes } from "./routes/projects/phases.js";
import { searchRoutes } from "./routes/search/index.js";
import { attachmentRoutes } from "./routes/attachments/index.js";
import { barcodeRoutes } from "./routes/barcode.js";
import { hobbyRoutes } from "./routes/hobbies/index.js";
import { hobbyRecipeRoutes } from "./routes/hobbies/recipes.js";
import { hobbySessionRoutes } from "./routes/hobbies/sessions.js";
import { hobbyMetricRoutes } from "./routes/hobbies/metrics.js";
import { hobbyLogRoutes } from "./routes/hobbies/logs.js";
import { hobbyLinkRoutes } from "./routes/hobbies/links.js";
import { hobbyShoppingListRoutes } from "./routes/hobbies/shopping-list.js";
import { publicShareRoutes } from "./routes/share-links/public.js";
import { shareLinkRoutes } from "./routes/share-links/index.js";

export const buildApp = () => {
  const app = Fastify({
    logger: true
  });

  app.register(cors, {
    origin: true
  });
  app.register(prismaPlugin);
  app.register(publicShareRoutes);
  app.register(authPlugin);
  app.register(storagePlugin);
  app.register(errorHandlerPlugin);
  app.register(healthRoutes);
  app.register(meRoutes);
  app.register(householdRoutes);
  app.register(householdInventoryAnalyticsRoutes);
  app.register(householdInventoryItemRoutes);
  app.register(householdInventoryTransactionRoutes);
  app.register(householdLinkPreviewRoutes);
  app.register(notificationRoutes);
  app.register(dashboardRoutes);
  app.register(assetRoutes);
  app.register(assetInventoryRoutes);
  app.register(timelineEntryRoutes);
  app.register(timelineRoutes);
  app.register(assetTransferRoutes);
  app.register(usageMetricRoutes);
  app.register(usageMetricAnalyticsRoutes);
  app.register(scheduleRoutes);
  app.register(scheduleInventoryRoutes);
  app.register(maintenanceLogRoutes);
  app.register(maintenanceLogPartRoutes);
  app.register(presetRoutes);
  app.register(serviceProviderRoutes);
  app.register(activityLogRoutes);
  app.register(complianceAnalyticsRoutes);
  app.register(comparativeAnalyticsRoutes);
  app.register(commentRoutes);
  app.register(costAnalyticsRoutes);
  app.register(exportRoutes);
  app.register(invitationRoutes);
  app.register(projectRoutes);
  app.register(projectBudgetAnalyticsRoutes);
  app.register(projectInventoryRoutes);
  app.register(projectPhaseRoutes);
  app.register(projectNoteRoutes);
  app.register(searchRoutes);
  app.register(barcodeRoutes);
  app.register(attachmentRoutes);
  app.register(shareLinkRoutes);
  app.register(hobbyRoutes);
  app.register(hobbyRecipeRoutes);
  app.register(hobbySessionRoutes);
  app.register(hobbyMetricRoutes);
  app.register(hobbyLogRoutes);
  app.register(hobbyLinkRoutes);
  app.register(hobbyShoppingListRoutes);

  return app;
};
