-- AlterTable
ALTER TABLE "IdeaCanvas" ADD COLUMN     "backgroundImageScale" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "backgroundImageX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "backgroundImageY" DOUBLE PRECISION NOT NULL DEFAULT 0;
